trigger:
  paths:
    include:
      - terraform/**
  branches:
    include:
      - main

stages:

- stage: Terraform
  displayName: 'Provision Infrastructure'

  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'

    pool:
      name: 'AgentVK'

    steps:

    - checkout: self

    - task: DownloadSecureFile@1
      name: download_ssh_key
      inputs:
        secureFile: 'id_rsa.pub'

    - powershell: |
        Write-Host "Copying SSH public key into Terraform module"

        $sshDir = "$env:USERPROFILE\.ssh"

        if (!(Test-Path $sshDir)) {
            New-Item -ItemType Directory -Path $sshDir
        }

        Copy-Item "$(download_ssh_key.secureFilePath)" "$sshDir\id_rsa.pub"

        # Copy into terraform module
        Copy-Item "$(download_ssh_key.secureFilePath)" "terraform\modules\compute\id_rsa.pub"

        Write-Host "Listing contents of terraform\modules\compute"
        Get-ChildItem terraform\modules\compute
      displayName: 'Extract SSH Public Key for Terraform'

    - task: AzureCLI@2
      displayName: 'Terraform Init Plan Apply'
      inputs:
        azureSubscription: 'vk-secret'
        scriptType: ps
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)\terraform
        inlineScript: |
          Write-Host "Starting Terraform deployment"

          terraform init -input=false
          terraform plan -input=false -var-file="envs/dev.tfvars"
          terraform apply -input=false -auto-approve -var-file="envs/dev.tfvars"
