variable "resource_group_name" {}
variable "location" {}
variable "admin_username" {}
variable "admin_password" {}
variable "vnet_subnet_id" {}
variable "application_name" {}
variable "environment" {}
variable "vm_size" {}
variable "ssh_public_key" {}
